version: '2.1'

executors:
  go-executor: 
    docker:
      - image: cimg/go:1.19.0
    resource_class: small

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run: echo "Placholder job"
  
  code_coverage:
    executor: go-executor
    steps:
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts 

workflows: 
  main_workflow:
      jobs:
        - build
        - code_coverage:
            requires: 
              - build
          
                