version: '2.1'

executors:
  go-executor: 
    docker:
      - image: cimg/go:1.19.0
    resource_class: small

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run: echo "Placholder job"
  
  code_coverage:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts 

  unit_testing: 
    executor: go-executor
    steps: 
      - checkout
      - run: 
          name: "create a folder for test results"
          command: | 
            mkdir -p /tmp/test-results
      - run: 
          name: "run unit tests and store results"
          command: |
            gotestsum --junitfile unit-tests.xml
      - store_test_results:
          path: /tmp/test-results         

workflows: 
  main_workflow:
      jobs:
        - build
        - code_coverage:
            requires: 
              - build
        - unit_testing:
            requires:
              - build
          
                